schema: 'https://docs.github.com/public/schema.docs.graphql'
extensions:
  codegen:
    generates:
      ./src/graphql.types.ts:
        plugins:
          - typescript
          - typescript-resolvers
